# Usa la imagen oficial de WordPress como base
FROM wordpress:6.7.1


# Establecer variables de entorno
ENV WORDPRESS_DB_NAME=dbmodel
ENV WORDPRESS_DB_USER=wpuser
ENV WORDPRESS_DB_PASSWORD=pa+55w0rd
ENV WORDPRESS_DB_HOST=db

# Establece el directorio de trabajo
WORKDIR /var/www/html


# Copia el script para configurar wp-config.php al contenedor
COPY setup_wp_config.sh .


# Copia el script SQL para configurar la base de datos
#COPY setup_db.sql /docker-entrypoint-initdb.d/

# Asegúrate de que el script sea ejecutable
#RUN chmod +x /usr/local/bin/setup_wp_config.sh

# Ejecuta el script para ajustar wp-config.php
#RUN /usr/local/bin/setup_wp_config.sh


# Expone el puerto 80
EXPOSE 80